# ---------------------------------------------------------------------------
global:
  checkNewVersion: false
  sendAnonymousUsage: false
# ---------------------------------------------------------------------------
api:
  debug: false
  dashboard: true
# ---------------------------------------------------------------------------
log:
  # Default [Available]
  # ERROR [PANIC, FATAL, ERROR, WARN, INFO, DEBUG]
  level: INFO
# ---------------------------------------------------------------------------
entryPoints:
  web:
    address: '0.0.0.0:80'
    http:
      redirections:
        entryPoint:
          to: websec
          scheme: https
  websec:
    address: '0.0.0.0:443'
# ---------------------------------------------------------------------------
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    network: proxy
    exposedByDefault: false
  file:
    directory: /conf.d
    watch: true
# ---------------------------------------------------------------------------
certificatesResolvers:
  le-http-01:
    acme:
      email: dns@poprocket.com
      storage: /acme.d/crt_store.json
      # # Uncomment the line to use Let's Encrypt's staging server,
      # # leave commented to go to prod.
      # #
      #caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web
