---
# hostname for target host
HOSTNAME: mars
HOSTS_INI_TARGET: mars

# Reconfiguration patterns of '/etc/hosts'
#
# search for
SEARCH_LINE: '^5\.45\.103\.43\s+.*$'
# replace with
REPLACE_LINE: "5.45.103.43       {{ HOSTNAME }}.poprocket.com   {{ HOSTNAME }}"

# path for Docker Compose project directories
CONTAINER_ROOT: /opt/containers

# Well known Reverse Proxy Network
PROXY_NETWORK_NAME: proxy
PROXY_NETWORK_CIDR: 172.30.0.0/16
PROXY_NETWORK_GATEWAY: 172.30.0.1

# admin user configuration
ADMIN_USER_NAME: toor
ADMIN_USER_SSH_KEY: "${HOME}/.ssh/id_rsa_poprocket_2023.pub"
ADMIN_USER_PASSWORD_HASH: "$6$IAVqWE8WuqMVU5RV$S.IV8gPhng8qjeO//tAc.8aNKDKACNVjTddsFIhsRwP1655ZQvu8.9D1b2VdbQrHEy3YrraRLngsWUwSbPuGj."
